### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by poorboy44** [bri-bri/yosemite-camping#2]
I wasn't able to get it to work. It looked like maybe the URLs have changed?

**Comment by bri-bri** [comment]
Yeah, major update to the recreation.gov site. Looking at it now, but I have low motivation to fix this because of how much criticism I've received for hosting this. At the very least I'll post an update within 2-3 days if I give up though!

**Comment by wmitchellUK** [comment]
Keep up the good work mate

**Comment by bri-bri** [comment]
update pushed... switched urls to ssl and just naively disabled ssl verification. Got an Upper Pines site for Oct 24 with a test:

`python campsites.py --start_date 2017-10-24 --end_date 2017-10-25`

**Comment by poorboy44** [comment]
What criticism? I think it's awesome!

Sent from my iPhone


On Sep 14, 2017, at 9:16 PM, Brian Hansen <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #2<https://github.com/bri-bri/yosemite-camping/issues/2>.

**Comment by bri-bri** [comment]
Thanks! People have (somewhat rightfully) pointed out that this gives a tech savvy minority an unfair advantage in snagging a campsite. One exact quote, for example, was "It’s an act of creating technology haves and technology have nots”  :man_shrugging:

**Comment by wmitchellUK** [comment]
For a few bucks they can always use one of the paid sites like yesyoucamp

**Comment by professorjedi** [comment]
sorry to revive the dead here, but does this still work?  I'm kinda new to python so trying to figure it out :)
